In [4]:
# getting set up - load packages and dataframes from previous steps 
library(tidyverse)
total_available <- read.csv("total_available.csv")

  Site Hectares avg_biomass total_biomass
1 1    1700     2411.009    4098716
2 2    1300     4117.127    5352265
3 3     900     5098.440    4588596

# Part 3: Estimating bison capacity 

Bison eat a lot of plants! One bison needs about 21,900 kg of biomass a year to live a healthy life. Since we have the total kg of biomass for each site now, we have an idea of which site might be best to introduce the bison. Bison are social animals and live in herds. It is important to the tribal agriculture managers to ensure that they can sustain a full herd population of at least 200 bison. 

Using `mutate()`, how many bison can each of these sites maintain?

In [7]:
# fill in the mutate function to create a new column of number of bison 
max_bison<-mutate(total_available, max_bison=total_biomass/21900) 
max_bison

write.csv(max_bison, "max_bison.csv", row.names=F)

  Site Hectares avg_biomass total_biomass max_bison
1 1    1700     2411.009    4098716       187.1560
2 2    1300     4117.127    5352265       244.3956
3 3     900     5098.440    4588596       209.5249

🧠✍️**Class Questions**

* Which site(s) would be able to maintain a healthy bison population (around 200 Bison)? 

* If you were to share these results with the local community and to other agriculture managers, how might you visualize this data to show which site might be best?

## Data visualization of max bison per site 

💻

In [6]:
# use ggplot here to write code that will visualize the max viable bison population at each site

## Lesson Recap